"""Product category database (seed data) — 10 materials x 60+ product categories.

Provides product_templates data used by the product designer wizard and
spec checker. Each template defines: material, category, names (zh/en),
suggested price range, margin, recommended POD platforms, DPI, and size specs.
"""

# ---------------------------------------------------------------------------
# Supported monetization platforms
# ---------------------------------------------------------------------------
PLATFORMS = [
    {"id": "printful", "name": "Printful", "mode": "pod", "region": "global"},
    {"id": "printify", "name": "Printify", "mode": "pod", "region": "global"},
    {"id": "redbubble", "name": "Redbubble", "mode": "pod", "region": "global"},
    {"id": "society6", "name": "Society6", "mode": "pod", "region": "global"},
    {"id": "gelato", "name": "Gelato", "mode": "pod", "region": "global"},
    {"id": "zazzle", "name": "Zazzle", "mode": "pod", "region": "global"},
    {"id": "yingge", "name": "印鸽", "mode": "pod", "region": "china"},
    {"id": "yunda", "name": "云打", "mode": "pod", "region": "china"},
    {"id": "modian", "name": "摩点", "mode": "crowdfunding", "region": "china"},
    {"id": "kickstarter", "name": "Kickstarter", "mode": "crowdfunding", "region": "global"},
    {"id": "creative_market", "name": "Creative Market", "mode": "licensing", "region": "global"},
    {"id": "envato", "name": "Envato", "mode": "licensing", "region": "global"},
    {"id": "gumroad", "name": "Gumroad", "mode": "digital", "region": "global"},
    {"id": "etsy", "name": "Etsy", "mode": "digital", "region": "global"},
]

# ---------------------------------------------------------------------------
# Product categories — 10 materials, 60+ categories
# ---------------------------------------------------------------------------
PRODUCT_CATEGORIES = [
    # ---- 1. 纸质/印刷类 (Paper) ----
    {
        "id": "cat_paper_art_print",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "art_print",
        "name_zh": "艺术微喷画/海报",
        "name_en": "Art Print / Poster",
        "suggested_price_cny": "89-299",
        "margin_pct": 50,
        "recommended_pod_platforms": ["printful", "printify", "redbubble"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 297, "height_mm": 420, "bleed_mm": 3},
    },
    {
        "id": "cat_paper_postcard",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "postcard",
        "name_zh": "明信片/贺卡",
        "name_en": "Postcard / Greeting Card",
        "suggested_price_cny": "15-39",
        "margin_pct": 40,
        "recommended_pod_platforms": ["redbubble", "zazzle"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 148, "height_mm": 105, "bleed_mm": 3},
    },
    {
        "id": "cat_paper_sticker",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "sticker",
        "name_zh": "贴纸/Stickers",
        "name_en": "Stickers",
        "suggested_price_cny": "8-29",
        "margin_pct": 60,
        "recommended_pod_platforms": ["redbubble"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 76, "height_mm": 76, "bleed_mm": 1.5},
    },
    {
        "id": "cat_paper_notebook",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "notebook",
        "name_zh": "手账本/笔记本",
        "name_en": "Notebook / Journal",
        "suggested_price_cny": "39-99",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 148, "height_mm": 210, "bleed_mm": 3},
    },
    {
        "id": "cat_paper_calendar",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "calendar",
        "name_zh": "日历/挂历",
        "name_en": "Calendar",
        "suggested_price_cny": "59-129",
        "margin_pct": 45,
        "recommended_pod_platforms": ["printful"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 297, "height_mm": 420, "bleed_mm": 3},
    },
    {
        "id": "cat_paper_bookmark",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "bookmark",
        "name_zh": "书签",
        "name_en": "Bookmark",
        "suggested_price_cny": "12-29",
        "margin_pct": 50,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 50, "height_mm": 148, "bleed_mm": 3},
    },
    {
        "id": "cat_paper_puzzle",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "puzzle",
        "name_zh": "拼图",
        "name_en": "Jigsaw Puzzle",
        "suggested_price_cny": "59-199",
        "margin_pct": 42,
        "recommended_pod_platforms": ["printful", "zazzle"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 250, "height_mm": 355, "bleed_mm": 3},
    },
    {
        "id": "cat_paper_wrapping",
        "material_category": "paper",
        "material_label_zh": "纸质/印刷类",
        "category": "wrapping_paper",
        "name_zh": "包装纸",
        "name_en": "Wrapping Paper",
        "suggested_price_cny": "29-79",
        "margin_pct": 45,
        "recommended_pod_platforms": ["zazzle"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 500, "height_mm": 700, "bleed_mm": 3},
    },
    # ---- 2. 纺织/服装类 (Textile) ----
    {
        "id": "cat_textile_tshirt",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "t_shirt",
        "name_zh": "T恤/短袖",
        "name_en": "T-Shirt",
        "suggested_price_cny": "99-199",
        "margin_pct": 42,
        "recommended_pod_platforms": ["printful", "printify", "redbubble"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 304, "height_mm": 406, "bleed_mm": 0, "safe_zone_mm": 12.7},
    },
    {
        "id": "cat_textile_hoodie",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "hoodie",
        "name_zh": "卫衣/帽衫",
        "name_en": "Hoodie",
        "suggested_price_cny": "199-399",
        "margin_pct": 42,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 355, "height_mm": 430, "bleed_mm": 0, "safe_zone_mm": 25},
    },
    {
        "id": "cat_textile_tote",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "tote_bag",
        "name_zh": "帆布袋/托特包",
        "name_en": "Tote Bag",
        "suggested_price_cny": "49-99",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 254, "height_mm": 330, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_pillow",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "pillow",
        "name_zh": "抱枕/靠垫",
        "name_en": "Throw Pillow",
        "suggested_price_cny": "69-149",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful", "printify", "redbubble"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 406, "height_mm": 406, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_cap",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "cap",
        "name_zh": "帽子",
        "name_en": "Cap / Hat",
        "suggested_price_cny": "69-149",
        "margin_pct": 45,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 150, "height_mm": 50, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_scarf",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "scarf",
        "name_zh": "围巾/丝巾",
        "name_en": "Scarf",
        "suggested_price_cny": "79-199",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 700, "height_mm": 700, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_socks",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "socks",
        "name_zh": "袜子",
        "name_en": "Socks",
        "suggested_price_cny": "39-79",
        "margin_pct": 42,
        "recommended_pod_platforms": ["printful"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 100, "height_mm": 200, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_blanket",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "blanket",
        "name_zh": "毯子/盖毯",
        "name_en": "Blanket",
        "suggested_price_cny": "129-299",
        "margin_pct": 45,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 150,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 1270, "height_mm": 1524, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_tapestry",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "tapestry",
        "name_zh": "挂毯/墙毯",
        "name_en": "Tapestry",
        "suggested_price_cny": "149-399",
        "margin_pct": 48,
        "recommended_pod_platforms": ["redbubble"],
        "moq": 1,
        "dpi_requirement": 150,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 1320, "height_mm": 1830, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_apron",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "apron",
        "name_zh": "围裙",
        "name_en": "Apron",
        "suggested_price_cny": "69-149",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 254, "height_mm": 355, "bleed_mm": 0},
    },
    {
        "id": "cat_textile_bath_towel",
        "material_category": "textile",
        "material_label_zh": "纺织/服装类",
        "category": "bath_towel",
        "name_zh": "浴巾/沙滩巾",
        "name_en": "Bath / Beach Towel",
        "suggested_price_cny": "99-249",
        "margin_pct": 45,
        "recommended_pod_platforms": ["printful"],
        "moq": 1,
        "dpi_requirement": 150,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 762, "height_mm": 1524, "bleed_mm": 0},
    },
    # ---- 3. 硬质/家居类 (Hard Goods) ----
    {
        "id": "cat_hard_mug",
        "material_category": "hard_goods",
        "material_label_zh": "硬质/家居类",
        "category": "mug",
        "name_zh": "陶瓷杯/马克杯",
        "name_en": "Ceramic Mug (11oz)",
        "suggested_price_cny": "59-129",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful", "printify", "redbubble"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 190, "height_mm": 80, "bleed_mm": 0},
    },
    {
        "id": "cat_hard_coaster",
        "material_category": "hard_goods",
        "material_label_zh": "硬质/家居类",
        "category": "coaster",
        "name_zh": "陶瓷杯垫",
        "name_en": "Ceramic Coaster",
        "suggested_price_cny": "29-59",
        "margin_pct": 52,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 96, "height_mm": 96, "bleed_mm": 3},
    },
    {
        "id": "cat_hard_enamel_mug",
        "material_category": "hard_goods",
        "material_label_zh": "硬质/家居类",
        "category": "enamel_mug",
        "name_zh": "搪瓷杯",
        "name_en": "Enamel Mug",
        "suggested_price_cny": "69-149",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 190, "height_mm": 80, "bleed_mm": 3},
    },
    {
        "id": "cat_hard_plate",
        "material_category": "hard_goods",
        "material_label_zh": "硬质/家居类",
        "category": "plate",
        "name_zh": "陶瓷盘/装饰盘",
        "name_en": "Decorative Plate",
        "suggested_price_cny": "89-199",
        "margin_pct": 48,
        "recommended_pod_platforms": ["zazzle"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 200, "height_mm": 200, "bleed_mm": 3},
    },
    {
        "id": "cat_hard_clock",
        "material_category": "hard_goods",
        "material_label_zh": "硬质/家居类",
        "category": "clock",
        "name_zh": "时钟/挂钟",
        "name_en": "Wall Clock",
        "suggested_price_cny": "99-249",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 250, "height_mm": 250, "bleed_mm": 3},
    },
    # ---- 4. 塑胶/3C电子类 (Plastic/3C) ----
    {
        "id": "cat_plastic_phonecase",
        "material_category": "plastic_3c",
        "material_label_zh": "塑胶/3C电子类",
        "category": "phone_case",
        "name_zh": "手机壳",
        "name_en": "Phone Case",
        "suggested_price_cny": "39-89",
        "margin_pct": 52,
        "recommended_pod_platforms": ["printful", "printify", "redbubble"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 75, "height_mm": 150, "bleed_mm": 3, "cutout_camera": True},
    },
    {
        "id": "cat_plastic_mousepad",
        "material_category": "plastic_3c",
        "material_label_zh": "塑胶/3C电子类",
        "category": "mouse_pad",
        "name_zh": "鼠标垫/桌垫",
        "name_en": "Mouse Pad / Desk Mat",
        "suggested_price_cny": "39-89",
        "margin_pct": 52,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 150,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 230, "height_mm": 200, "bleed_mm": 3},
    },
    {
        "id": "cat_plastic_airpods_case",
        "material_category": "plastic_3c",
        "material_label_zh": "塑胶/3C电子类",
        "category": "airpods_case",
        "name_zh": "AirPods保护壳",
        "name_en": "AirPods Case",
        "suggested_price_cny": "29-69",
        "margin_pct": 55,
        "recommended_pod_platforms": ["printful"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 60, "height_mm": 55, "bleed_mm": 3},
    },
    {
        "id": "cat_plastic_acrylic_stand",
        "material_category": "plastic_3c",
        "material_label_zh": "塑胶/3C电子类",
        "category": "acrylic_stand",
        "name_zh": "亚克力立牌",
        "name_en": "Acrylic Stand",
        "suggested_price_cny": "39-99",
        "margin_pct": 52,
        "recommended_pod_platforms": [],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 80, "height_mm": 120, "bleed_mm": 3},
    },
    {
        "id": "cat_plastic_badge",
        "material_category": "plastic_3c",
        "material_label_zh": "塑胶/3C电子类",
        "category": "badge",
        "name_zh": "徽章/胸针",
        "name_en": "Badge / Pin",
        "suggested_price_cny": "15-49",
        "margin_pct": 52,
        "recommended_pod_platforms": ["zazzle"],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 37, "height_mm": 37, "bleed_mm": 1},
    },
    {
        "id": "cat_plastic_keychain",
        "material_category": "plastic_3c",
        "material_label_zh": "塑胶/3C电子类",
        "category": "keychain",
        "name_zh": "钥匙扣/挂件",
        "name_en": "Keychain",
        "suggested_price_cny": "19-49",
        "margin_pct": 55,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 40, "height_mm": 60, "bleed_mm": 2},
    },
    {
        "id": "cat_plastic_laptop_skin",
        "material_category": "plastic_3c",
        "material_label_zh": "塑胶/3C电子类",
        "category": "laptop_skin",
        "name_zh": "笔记本贴膜",
        "name_en": "Laptop Skin / Sticker",
        "suggested_price_cny": "49-129",
        "margin_pct": 52,
        "recommended_pod_platforms": ["redbubble"],
        "moq": 1,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 330, "height_mm": 230, "bleed_mm": 3},
    },
    # ---- 5. 金属类 (Metal) ----
    {
        "id": "cat_metal_bookmark",
        "material_category": "metal",
        "material_label_zh": "金属类",
        "category": "metal_bookmark",
        "name_zh": "金属书签",
        "name_en": "Metal Bookmark",
        "suggested_price_cny": "39-89",
        "margin_pct": 52,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 30, "height_mm": 120, "bleed_mm": 3},
    },
    {
        "id": "cat_metal_badge",
        "material_category": "metal",
        "material_label_zh": "金属类",
        "category": "metal_badge",
        "name_zh": "金属徽章",
        "name_en": "Metal Badge / Enamel Pin",
        "suggested_price_cny": "29-79",
        "margin_pct": 52,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 30, "height_mm": 30, "bleed_mm": 2},
    },
    {
        "id": "cat_metal_keychain",
        "material_category": "metal",
        "material_label_zh": "金属类",
        "category": "metal_keychain",
        "name_zh": "金属钥匙扣",
        "name_en": "Metal Keychain",
        "suggested_price_cny": "29-79",
        "margin_pct": 52,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 40, "height_mm": 60, "bleed_mm": 2},
    },
    {
        "id": "cat_metal_necklace",
        "material_category": "metal",
        "material_label_zh": "金属类",
        "category": "necklace",
        "name_zh": "项链/吊坠",
        "name_en": "Necklace / Pendant",
        "suggested_price_cny": "69-299",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 20, "height_mm": 30, "bleed_mm": 1},
    },
    {
        "id": "cat_metal_earrings",
        "material_category": "metal",
        "material_label_zh": "金属类",
        "category": "earrings",
        "name_zh": "耳环/耳钉",
        "name_en": "Earrings",
        "suggested_price_cny": "49-199",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 15, "height_mm": 25, "bleed_mm": 1},
    },
    {
        "id": "cat_metal_ornament",
        "material_category": "metal",
        "material_label_zh": "金属类",
        "category": "ornament",
        "name_zh": "金属摆件",
        "name_en": "Metal Ornament",
        "suggested_price_cny": "99-399",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 150,
        "color_mode": "N/A",
        "file_format": "STL/OBJ",
        "transparent_bg": False,
        "size_spec": {"width_mm": 100, "height_mm": 150, "bleed_mm": 0},
    },
    # ---- 6. 木材/竹材类 (Wood) ----
    {
        "id": "cat_wood_coaster",
        "material_category": "wood",
        "material_label_zh": "木材/竹材类",
        "category": "wood_coaster",
        "name_zh": "木质杯垫",
        "name_en": "Wooden Coaster",
        "suggested_price_cny": "29-59",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful"],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 100, "height_mm": 100, "bleed_mm": 3},
    },
    {
        "id": "cat_wood_cutting_board",
        "material_category": "wood",
        "material_label_zh": "木材/竹材类",
        "category": "wood_cutting_board",
        "name_zh": "木质切菜板/餐板",
        "name_en": "Wooden Cutting / Serving Board",
        "suggested_price_cny": "89-249",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful"],
        "moq": 25,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 280, "height_mm": 200, "bleed_mm": 3},
    },
    {
        "id": "cat_wood_photo_frame",
        "material_category": "wood",
        "material_label_zh": "木材/竹材类",
        "category": "wood_photo_frame",
        "name_zh": "木质相框",
        "name_en": "Wooden Photo Frame",
        "suggested_price_cny": "59-199",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 210, "height_mm": 297, "bleed_mm": 3},
    },
    # ---- 7. 皮革类 (Leather) ----
    {
        "id": "cat_leather_wallet",
        "material_category": "leather",
        "material_label_zh": "皮革类",
        "category": "leather_wallet",
        "name_zh": "皮质卡包/钱包",
        "name_en": "Leather Card Wallet",
        "suggested_price_cny": "99-299",
        "margin_pct": 52,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 100, "height_mm": 70, "bleed_mm": 3},
    },
    {
        "id": "cat_leather_notebook_cover",
        "material_category": "leather",
        "material_label_zh": "皮革类",
        "category": "leather_notebook_cover",
        "name_zh": "皮质笔记本套",
        "name_en": "Leather Notebook Cover",
        "suggested_price_cny": "129-349",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 50,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 320, "height_mm": 220, "bleed_mm": 3},
    },
    {
        "id": "cat_leather_luggage_tag",
        "material_category": "leather",
        "material_label_zh": "皮革类",
        "category": "leather_luggage_tag",
        "name_zh": "皮质行李牌",
        "name_en": "Leather Luggage Tag",
        "suggested_price_cny": "59-149",
        "margin_pct": 55,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "AI/PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 70, "height_mm": 120, "bleed_mm": 3},
    },
    # ---- 8. 儿童/玩具类 (Toys) ----
    {
        "id": "cat_toy_plush",
        "material_category": "toys",
        "material_label_zh": "儿童/玩具类",
        "category": "plush_toy",
        "name_zh": "毛绒玩具/玩偶",
        "name_en": "Plush Toy",
        "suggested_price_cny": "89-299",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 200,
        "dpi_requirement": 150,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 200, "height_mm": 300, "bleed_mm": 0},
    },
    {
        "id": "cat_toy_figure",
        "material_category": "toys",
        "material_label_zh": "儿童/玩具类",
        "category": "action_figure",
        "name_zh": "手办/人偶",
        "name_en": "Action Figure / Figurine",
        "suggested_price_cny": "199-999",
        "margin_pct": 48,
        "recommended_pod_platforms": [],
        "moq": 300,
        "dpi_requirement": 150,
        "color_mode": "N/A",
        "file_format": "STL/OBJ",
        "transparent_bg": False,
        "size_spec": {"width_mm": 100, "height_mm": 150, "bleed_mm": 0},
    },
    {
        "id": "cat_toy_vinyl",
        "material_category": "toys",
        "material_label_zh": "儿童/玩具类",
        "category": "vinyl_figure",
        "name_zh": "搪胶/Sofubi玩具",
        "name_en": "Vinyl / Sofubi Figure",
        "suggested_price_cny": "149-599",
        "margin_pct": 50,
        "recommended_pod_platforms": [],
        "moq": 200,
        "dpi_requirement": 150,
        "color_mode": "N/A",
        "file_format": "STL/OBJ",
        "transparent_bg": False,
        "size_spec": {"width_mm": 120, "height_mm": 180, "bleed_mm": 0},
    },
    {
        "id": "cat_toy_card_game",
        "material_category": "toys",
        "material_label_zh": "儿童/玩具类",
        "category": "card_game",
        "name_zh": "集换式卡牌/桌游",
        "name_en": "Trading Card / Board Game",
        "suggested_price_cny": "49-299",
        "margin_pct": 42,
        "recommended_pod_platforms": [],
        "moq": 500,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "PDF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 63, "height_mm": 88, "bleed_mm": 3},
    },
    # ---- 9. 数字产品类 (Digital) ----
    {
        "id": "cat_digital_brushes",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_brushes",
        "name_zh": "笔刷/素材包",
        "name_en": "Brush / Asset Pack",
        "suggested_price_cny": "35-350",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "ZIP",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_digital_template",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_template",
        "name_zh": "设计模板",
        "name_en": "Design Template",
        "suggested_price_cny": "70-700",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "ZIP",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_digital_font",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_font",
        "name_zh": "字体",
        "name_en": "Font",
        "suggested_price_cny": "70-700",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "OTF/TTF",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_digital_stl",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_3d",
        "name_zh": "3D打印模型 (STL)",
        "name_en": "3D Print Model (STL)",
        "suggested_price_cny": "35-350",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "STL/OBJ",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_digital_clipart",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_clipart",
        "name_zh": "PNG素材/贴纸包",
        "name_en": "PNG Clipart / Sticker Pack",
        "suggested_price_cny": "15-150",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "PNG/ZIP",
        "transparent_bg": True,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_digital_tutorial",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_tutorial",
        "name_zh": "教程/课程",
        "name_en": "Tutorial / Course",
        "suggested_price_cny": "49-499",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "MP4/PDF/ZIP",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_digital_plugin",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_plugin",
        "name_zh": "插件/扩展",
        "name_en": "Plugin / Extension",
        "suggested_price_cny": "35-700",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "ZIP",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_digital_music_loop",
        "material_category": "digital",
        "material_label_zh": "数字产品类",
        "category": "digital_music",
        "name_zh": "音乐/音效素材",
        "name_en": "Music / Sound Effect Loop",
        "suggested_price_cny": "15-150",
        "margin_pct": 95,
        "recommended_pod_platforms": [],
        "moq": 0,
        "dpi_requirement": 0,
        "color_mode": "N/A",
        "file_format": "MP3/WAV/ZIP",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    # ---- 10. 特殊品类 (Special) ----
    {
        "id": "cat_special_ar",
        "material_category": "special",
        "material_label_zh": "特殊品类",
        "category": "ar_product",
        "name_zh": "AR交互产品",
        "name_en": "AR Interactive Product",
        "suggested_price_cny": "199-599",
        "margin_pct": 60,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 0,
        "color_mode": "sRGB",
        "file_format": "N/A",
        "transparent_bg": False,
        "size_spec": {"width_mm": 0, "height_mm": 0, "bleed_mm": 0},
    },
    {
        "id": "cat_special_hologram",
        "material_category": "special",
        "material_label_zh": "特殊品类",
        "category": "hologram",
        "name_zh": "全息/激光膜制品",
        "name_en": "Holographic / Laser Film Product",
        "suggested_price_cny": "29-99",
        "margin_pct": 55,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "PNG/AI",
        "transparent_bg": False,
        "size_spec": {"width_mm": 76, "height_mm": 76, "bleed_mm": 1.5},
    },
    {
        "id": "cat_special_canvas",
        "material_category": "special",
        "material_label_zh": "特殊品类",
        "category": "canvas",
        "name_zh": "帆布画/油画布打印",
        "name_en": "Canvas Print",
        "suggested_price_cny": "149-599",
        "margin_pct": 48,
        "recommended_pod_platforms": ["printful", "printify"],
        "moq": 1,
        "dpi_requirement": 150,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 406, "height_mm": 508, "bleed_mm": 38},
    },
    {
        "id": "cat_special_led",
        "material_category": "special",
        "material_label_zh": "特殊品类",
        "category": "led_lamp",
        "name_zh": "氛围灯/小夜灯",
        "name_en": "LED Mood Light / Night Light",
        "suggested_price_cny": "69-199",
        "margin_pct": 52,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 300,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 100, "height_mm": 150, "bleed_mm": 3},
    },
    {
        "id": "cat_special_embroidered_patch",
        "material_category": "special",
        "material_label_zh": "特殊品类",
        "category": "embroidered_patch",
        "name_zh": "刺绣布贴/徽章",
        "name_en": "Embroidered Patch",
        "suggested_price_cny": "19-69",
        "margin_pct": 50,
        "recommended_pod_platforms": [],
        "moq": 100,
        "dpi_requirement": 200,
        "color_mode": "sRGB",
        "file_format": "PNG",
        "transparent_bg": True,
        "size_spec": {"width_mm": 50, "height_mm": 50, "bleed_mm": 2},
    },
    {
        "id": "cat_special_washi_tape",
        "material_category": "special",
        "material_label_zh": "特殊品类",
        "category": "washi_tape",
        "name_zh": "和纸胶带/手账胶带",
        "name_en": "Washi Tape / Masking Tape",
        "suggested_price_cny": "15-49",
        "margin_pct": 55,
        "recommended_pod_platforms": [],
        "moq": 200,
        "dpi_requirement": 300,
        "color_mode": "CMYK",
        "file_format": "PNG",
        "transparent_bg": False,
        "size_spec": {"width_mm": 15, "height_mm": 5000, "bleed_mm": 1},
    },
]


# ---------------------------------------------------------------------------
# Material categories for the wizard
# ---------------------------------------------------------------------------
MATERIAL_CATEGORIES = [
    {"id": "paper", "label_zh": "纸质/印刷类", "icon": "📄"},
    {"id": "textile", "label_zh": "纺织/服装类", "icon": "👕"},
    {"id": "hard_goods", "label_zh": "硬质/家居类", "icon": "🏠"},
    {"id": "plastic_3c", "label_zh": "塑胶/3C电子类", "icon": "📱"},
    {"id": "metal", "label_zh": "金属/珠宝类", "icon": "🔩"},
    {"id": "wood", "label_zh": "木材/竹材类", "icon": "🪵"},
    {"id": "leather", "label_zh": "皮革类", "icon": "👜"},
    {"id": "toys", "label_zh": "儿童/玩具类", "icon": "🧸"},
    {"id": "digital", "label_zh": "数字产品类", "icon": "💻"},
    {"id": "special", "label_zh": "特殊品类", "icon": "✨"},
]

# Monetization paths
MONETIZATION_PATHS = [
    {
        "id": "pod",
        "name_zh": "POD按需打印",
        "name_en": "Print on Demand",
        "icon": "🖨️",
        "desc": "零库存，按需打印，对接全球POD平台",
        "pros": ["零库存风险", "1件起订", "全球配送"],
        "cons": ["单件成本较高", "利润空间有限", "依赖平台品质"],
    },
    {
        "id": "crowdfunding",
        "name_zh": "众筹验证",
        "name_en": "Crowdfunding",
        "icon": "🚀",
        "desc": "先验证需求再量产，创意风险最小化",
        "pros": ["验证市场需求", "前期现金流", "社区建设"],
        "cons": ["需要营销推广", "平台抽成", "交付压力"],
    },
    {
        "id": "licensing",
        "name_zh": "IP授权",
        "name_en": "IP Licensing",
        "icon": "📜",
        "desc": "将设计授权给第三方使用，持续收益",
        "pros": ["持续被动收入", "无需生产", "规模化收益"],
        "cons": ["需要IP知名度", "维权成本", "收益分散"],
    },
    {
        "id": "custom_mfg",
        "name_zh": "按需制造",
        "name_en": "Custom Manufacturing",
        "icon": "🏭",
        "desc": "批量生产，品牌完全控制，利润最高",
        "pros": ["利润空间大", "品牌控制", "品质可控"],
        "cons": ["需要起订量", "库存风险", "前期投入"],
    },
    {
        "id": "digital",
        "name_zh": "数字产品",
        "name_en": "Digital Products",
        "icon": "💾",
        "desc": "零物流，零边际成本，即时交付",
        "pros": ["零边际成本", "零物流", "即时交付"],
        "cons": ["盗版风险", "定价竞争激烈", "需要持续更新"],
    },
]


def get_categories_by_material(material_id: str) -> list:
    """Return product categories filtered by material."""
    return [c for c in PRODUCT_CATEGORIES if c["material_category"] == material_id]


def get_category_by_id(category_id: str) -> dict | None:
    """Return a single product category by its id."""
    for c in PRODUCT_CATEGORIES:
        if c["id"] == category_id:
            return c
    return None


def get_monetization_path(path_id: str) -> dict | None:
    """Return a single monetization path by id."""
    for p in MONETIZATION_PATHS:
        if p["id"] == path_id:
            return p
    return None
