"""add_contract_market_core_tables

Revision ID: 5966ef53f125
Revises: b6184669abcd
Create Date: 2026-07-21 02:18:04.438064
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5966ef53f125'
down_revision: Union[str, None] = 'b6184669abcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_badges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('badge_key', sa.String(length=50), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('badge_description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_key')
    )
    op.create_index('idx_achievement_active', 'achievement_badges', ['is_active'], unique=False)
    op.create_index('idx_achievement_key', 'achievement_badges', ['badge_key'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount_yuan', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('subtotal_yuan', sa.Float(), nullable=False),
    sa.Column('tax_amount_yuan', sa.Float(), nullable=True),
    sa.Column('total_yuan', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_proof_path', sa.String(length=500), nullable=True),
    sa.Column('is_auto_renewal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('idx_invoice_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoice_user', 'invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('creator_type', sa.String(length=50), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leaderboard_creator', 'leaderboard_entries', ['creator_type'], unique=False)
    op.create_index('idx_leaderboard_period', 'leaderboard_entries', ['period'], unique=False)
    op.create_index('idx_leaderboard_user', 'leaderboard_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    op.create_table('pod_settlements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('total_sales_yuan', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost_yuan', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('creator_earnings_yuan', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('platform_fee_yuan', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settle_user_period', 'pod_settlements', ['user_id', 'period'], unique=False)
    op.create_index(op.f('ix_pod_settlements_status'), 'pod_settlements', ['status'], unique=False)
    op.create_index(op.f('ix_pod_settlements_user_id'), 'pod_settlements', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('badge_id', sa.String(length=32), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['achievement_badges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_achievement_unique', 'user_achievements', ['user_id', 'badge_id'], unique=True)
    op.create_index('idx_user_achievement_user', 'user_achievements', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('amount_yuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_balance_yuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_yuan', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount_yuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('account_info', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.String(length=32), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_withdraw_created', 'withdrawal_requests', ['created_at'], unique=False)
    op.create_index('idx_withdraw_status', 'withdrawal_requests', ['status'], unique=False)
    op.create_index('idx_withdraw_user', 'withdrawal_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_status'), 'withdrawal_requests', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_user_id'), 'withdrawal_requests', ['user_id'], unique=False)
    op.create_table('contract_instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_id', sa.String(length=32), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('scope_usage', sa.String(length=50), nullable=True),
    sa.Column('scope_geography', sa.String(length=50), nullable=True),
    sa.Column('scope_duration', sa.String(length=50), nullable=True),
    sa.Column('scope_medium', sa.String(length=50), nullable=True),
    sa.Column('scope_print_limit', sa.Integer(), nullable=True),
    sa.Column('scope_revenue_cap', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('split_rules_json', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.Column('escrowed_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('insurance_product_id', sa.String(length=32), nullable=True),
    sa.Column('insurance_policy_no', sa.String(length=100), nullable=True),
    sa.Column('insurance_premium', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('escrow_provider', sa.String(length=30), nullable=True),
    sa.Column('escrow_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('trader_id', sa.String(length=32), nullable=True),
    sa.Column('verified', sa.String(length=30), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trader_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_creator', 'contract_instances', ['creator_id'], unique=False)
    op.create_index('idx_contract_published', 'contract_instances', ['published_at'], unique=False)
    op.create_index('idx_contract_status', 'contract_instances', ['status'], unique=False)
    op.create_index('idx_contract_verified', 'contract_instances', ['verified'], unique=False)
    op.create_index('idx_contract_work', 'contract_instances', ['work_id'], unique=False)
    op.create_index(op.f('ix_contract_instances_creator_id'), 'contract_instances', ['creator_id'], unique=False)
    op.create_table('pod_settlement_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('settlement_id', sa.String(length=32), nullable=False),
    sa.Column('sale_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('sale_amount_yuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_yuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creator_earning_yuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee_yuan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['pod_products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['pod_sales.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['pod_settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_settlement', 'pod_settlement_items', ['settlement_id'], unique=False)
    op.create_table('subscription_auto_renewals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subscriber_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_renewal_attempt', sa.DateTime(), nullable=True),
    sa.Column('next_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('max_failed_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscription_subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id')
    )
    op.create_index('idx_auto_renewal_enabled', 'subscription_auto_renewals', ['enabled'], unique=False)
    op.create_index('idx_auto_renewal_subscriber', 'subscription_auto_renewals', ['subscriber_id'], unique=False)
    op.create_table('contract_matchings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('participant_type', sa.String(length=30), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(length=30), nullable=True),
    sa.Column('counter_offer_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_matching_contract', 'contract_matchings', ['contract_id'], unique=False)
    op.create_index('idx_contract_matching_participant', 'contract_matchings', ['participant_id'], unique=False)
    op.create_index(op.f('ix_contract_matchings_contract_id'), 'contract_matchings', ['contract_id'], unique=False)
    op.create_table('split_execution_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('execution_batch', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('executor', sa.String(length=30), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_split_exec_batch', 'split_execution_logs', ['execution_batch'], unique=False)
    op.create_index('idx_split_exec_contract', 'split_execution_logs', ['contract_id'], unique=False)
    op.create_index(op.f('ix_split_execution_logs_contract_id'), 'split_execution_logs', ['contract_id'], unique=False)
    op.create_table('split_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('participant_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('quote_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('quoted_at', sa.DateTime(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_split_rule_contract', 'split_rules', ['contract_id'], unique=False)
    op.create_index('idx_split_rule_participant', 'split_rules', ['participant_id'], unique=False)
    op.create_index(op.f('ix_split_rules_contract_id'), 'split_rules', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_index('idx_rfqs_status', table_name='rfqs')
    op.drop_index(op.f('ix_revenue_records_user_id'), table_name='revenue_records')
    op.alter_column('revenue_records', 'platform',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('etsy_orders', 'listing_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('ai_creation_sessions', 'prompt',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('ai_creation_sessions', 'updated_at')
    op.drop_index(op.f('ix_split_rules_contract_id'), table_name='split_rules')
    op.drop_index('idx_split_rule_participant', table_name='split_rules')
    op.drop_index('idx_split_rule_contract', table_name='split_rules')
    op.drop_table('split_rules')
    op.drop_index(op.f('ix_split_execution_logs_contract_id'), table_name='split_execution_logs')
    op.drop_index('idx_split_exec_contract', table_name='split_execution_logs')
    op.drop_index('idx_split_exec_batch', table_name='split_execution_logs')
    op.drop_table('split_execution_logs')
    op.drop_index(op.f('ix_contract_matchings_contract_id'), table_name='contract_matchings')
    op.drop_index('idx_contract_matching_participant', table_name='contract_matchings')
    op.drop_index('idx_contract_matching_contract', table_name='contract_matchings')
    op.drop_table('contract_matchings')
    op.drop_index('idx_auto_renewal_subscriber', table_name='subscription_auto_renewals')
    op.drop_index('idx_auto_renewal_enabled', table_name='subscription_auto_renewals')
    op.drop_table('subscription_auto_renewals')
    op.drop_index('idx_item_settlement', table_name='pod_settlement_items')
    op.drop_table('pod_settlement_items')
    op.drop_index(op.f('ix_contract_instances_creator_id'), table_name='contract_instances')
    op.drop_index('idx_contract_work', table_name='contract_instances')
    op.drop_index('idx_contract_verified', table_name='contract_instances')
    op.drop_index('idx_contract_status', table_name='contract_instances')
    op.drop_index('idx_contract_published', table_name='contract_instances')
    op.drop_index('idx_contract_creator', table_name='contract_instances')
    op.drop_table('contract_instances')
    op.drop_index(op.f('ix_withdrawal_requests_user_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_status'), table_name='withdrawal_requests')
    op.drop_index('idx_withdraw_user', table_name='withdrawal_requests')
    op.drop_index('idx_withdraw_status', table_name='withdrawal_requests')
    op.drop_index('idx_withdraw_created', table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index('idx_user_achievement_user', table_name='user_achievements')
    op.drop_index('idx_user_achievement_unique', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_pod_settlements_user_id'), table_name='pod_settlements')
    op.drop_index(op.f('ix_pod_settlements_status'), table_name='pod_settlements')
    op.drop_index('idx_settle_user_period', table_name='pod_settlements')
    op.drop_table('pod_settlements')
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_index('idx_leaderboard_user', table_name='leaderboard_entries')
    op.drop_index('idx_leaderboard_period', table_name='leaderboard_entries')
    op.drop_index('idx_leaderboard_creator', table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index('idx_invoice_user', table_name='invoices')
    op.drop_index('idx_invoice_status', table_name='invoices')
    op.drop_index('idx_invoice_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_achievement_key', table_name='achievement_badges')
    op.drop_index('idx_achievement_active', table_name='achievement_badges')
    op.drop_table('achievement_badges')
    # ### end Alembic commands ###
