"""initial schema

Revision ID: 76540445f941
Revises: 
Create Date: 2026-06-23 02:40:18.298087
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '76540445f941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_listings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=True),
    sa.Column('product_template_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('spec_validation', sa.JSON(), nullable=True),
    sa.Column('spec_validated_at', sa.DateTime(), nullable=True),
    sa.Column('variant_sku', sa.String(length=100), nullable=True),
    sa.Column('variant_name', sa.String(length=200), nullable=True),
    sa.Column('monetization_path', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mockup_image_path', sa.String(length=2000), nullable=True),
    sa.Column('design_file_path', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_template_id'], ['product_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dl_path', 'design_listings', ['monetization_path'], unique=False)
    op.create_index('idx_dl_status', 'design_listings', ['status'], unique=False)
    op.create_index('idx_dl_template', 'design_listings', ['product_template_id'], unique=False)
    op.create_index('idx_dl_work', 'design_listings', ['work_id'], unique=False)
    op.create_table('design_template_compatibility',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('product_template_id', sa.String(length=32), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('spec_result', sa.String(length=20), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=True),
    sa.Column('compatible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dtc_compatible', 'design_template_compatibility', ['work_id', 'compatible'], unique=False)
    op.create_index('idx_dtc_template', 'design_template_compatibility', ['product_template_id'], unique=False)
    op.create_index('idx_dtc_work', 'design_template_compatibility', ['work_id'], unique=False)
    op.create_index('uq_dtc', 'design_template_compatibility', ['work_id', 'product_template_id'], unique=True)
    op.create_table('publish_analytics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_date', 'publish_analytics', ['date'], unique=False)
    op.create_index('idx_analytics_platform', 'publish_analytics', ['platform'], unique=False)
    op.create_table('publish_contents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('image_paths', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_product', 'publish_contents', ['product_id'], unique=False)
    op.create_index('idx_content_work', 'publish_contents', ['work_id'], unique=False)
    op.create_table('publish_schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('listing_id', sa.String(length=32), nullable=True),
    sa.Column('work_id', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['design_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_platform', 'publish_schedules', ['platform'], unique=False)
    op.create_index('idx_schedule_status', 'publish_schedules', ['status'], unique=False)
    op.create_index('idx_schedule_time', 'publish_schedules', ['scheduled_time'], unique=False)
    op.alter_column('works', 'completion_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # Batch-context operations for SQLite compatibility (ALTER TABLE)
    with op.batch_alter_table('campaigns') as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_campaign_listing', ['listing_id'], unique=False)

    with op.batch_alter_table('licenses') as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_license_listing', ['listing_id'], unique=False)

    with op.batch_alter_table('orders') as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('product_publishings') as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('revenue_records') as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenue_records') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('product_publishings') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('orders') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('licenses') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_license_listing')
        batch_op.drop_column('listing_id')

    with op.batch_alter_table('campaigns') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_campaign_listing')
        batch_op.drop_column('listing_id')

    op.alter_column('works', 'completion_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_constraint(None, 'revenue_records', type_='foreignkey')
    op.drop_column('revenue_records', 'listing_id')
    op.drop_constraint(None, 'product_publishings', type_='foreignkey')
    op.drop_column('product_publishings', 'listing_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'listing_id')
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.drop_index('idx_license_listing', table_name='licenses')
    op.drop_column('licenses', 'listing_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index('idx_campaign_listing', table_name='campaigns')
    op.drop_column('campaigns', 'listing_id')
    op.drop_index('idx_schedule_time', table_name='publish_schedules')
    op.drop_index('idx_schedule_status', table_name='publish_schedules')
    op.drop_index('idx_schedule_platform', table_name='publish_schedules')
    op.drop_table('publish_schedules')
    op.drop_index('idx_content_work', table_name='publish_contents')
    op.drop_index('idx_content_product', table_name='publish_contents')
    op.drop_table('publish_contents')
    op.drop_index('idx_analytics_platform', table_name='publish_analytics')
    op.drop_index('idx_analytics_date', table_name='publish_analytics')
    op.drop_table('publish_analytics')
    op.drop_index('uq_dtc', table_name='design_template_compatibility')
    op.drop_index('idx_dtc_work', table_name='design_template_compatibility')
    op.drop_index('idx_dtc_template', table_name='design_template_compatibility')
    op.drop_index('idx_dtc_compatible', table_name='design_template_compatibility')
    op.drop_table('design_template_compatibility')
    op.drop_index('idx_dl_work', table_name='design_listings')
    op.drop_index('idx_dl_template', table_name='design_listings')
    op.drop_index('idx_dl_status', table_name='design_listings')
    op.drop_index('idx_dl_path', table_name='design_listings')
    op.drop_table('design_listings')
    # ### end Alembic commands ###
