"""add_notary_and_c2pa_tables

Revision ID: a1b2c3d4e5f6
Revises: 5966ef53f125
Create Date: 2026-07-21 03:00:00.000000
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '5966ef53f125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notary_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_url', sa.String(length=2000), nullable=True),
    sa.Column('transaction_hash', sa.String(length=128), nullable=True),
    sa.Column('block_height', sa.String(length=50), nullable=True),
    sa.Column('blockchain', sa.String(length=50), nullable=True),
    sa.Column('certificate_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, server_default='unverified'),
    sa.Column('fee', sa.Float(), nullable=True, server_default='0.0'),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True, server_default='unpaid'),
    sa.Column('qr_code_url', sa.String(length=2000), nullable=True),
    sa.Column('evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notary_work', 'notary_records', ['work_id'], unique=False)
    op.create_index('idx_notary_status', 'notary_records', ['status'], unique=False)
    op.create_index('idx_notary_work_platform', 'notary_records', ['work_id', 'platform'], unique=False)
    op.create_index('idx_notary_platform', 'notary_records', ['platform'], unique=False)
    op.create_table('notary_audit_trails',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('notary_record_id', sa.String(length=32), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, server_default='success'),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notary_record_id'], ['notary_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_notary_record', 'notary_audit_trails', ['notary_record_id'], unique=False)
    op.create_index('idx_audit_step', 'notary_audit_trails', ['step'], unique=False)
    op.create_table('c2pa_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'),
    sa.Column('validator_url', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_c2pa_work', 'c2pa_records', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_c2pa_work', table_name='c2pa_records')
    op.drop_table('c2pa_records')
    op.drop_index('idx_audit_step', table_name='notary_audit_trails')
    op.drop_index('idx_audit_notary_record', table_name='notary_audit_trails')
    op.drop_table('notary_audit_trails')
    op.drop_index('idx_notary_platform', table_name='notary_records')
    op.drop_index('idx_notary_work_platform', table_name='notary_records')
    op.drop_index('idx_notary_status', table_name='notary_records')
    op.drop_index('idx_notary_work', table_name='notary_records')
    op.drop_table('notary_records')
    # ### end Alembic commands ###
