"""add_participant_roles_to_users

Revision ID: d62359dbdd00
Revises: 5966ef53f125
Create Date: 2026-07-21 02:34:07.815001
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd62359dbdd00'
down_revision: Union[str, None] = '5966ef53f125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('participant_roles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_platform_operator', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_payment_provider', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_insurer', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_logistics', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_logistics')
    op.drop_column('users', 'is_insurer')
    op.drop_column('users', 'is_payment_provider')
    op.drop_column('users', 'is_platform_operator')
    op.drop_column('users', 'participant_roles')
    # ### end Alembic commands ###
