"""add P2/P3 columns and tables

Revision ID: e34135f4e811
Revises: 76540445f941
Create Date: 2026-06-23 13:55:23.367118
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e34135f4e811'
down_revision: Union[str, None] = '76540445f941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('payment_terms', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comp_status', 'commission_projects', ['status'], unique=False)
    op.create_index('idx_comp_user', 'commission_projects', ['user_id'], unique=False)
    op.create_table('project_file_formats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pff_ext', 'project_file_formats', ['extension'], unique=False)
    op.create_table('rfq_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rfq_status', 'rfq_requests', ['status'], unique=False)
    op.create_index('idx_rfq_user', 'rfq_requests', ['user_id'], unique=False)
    op.create_table('subscription_tiers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tier_active', 'subscription_tiers', ['is_active'], unique=False)
    op.create_index('idx_tier_name', 'subscription_tiers', ['name'], unique=False)
    op.create_table('video_fingerprint_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('frame_interval', sa.Integer(), nullable=True),
    sa.Column('hash_algorithm', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('sender_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['commission_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_project', 'commission_messages', ['project_id'], unique=False)
    op.create_index('idx_msg_sender', 'commission_messages', ['sender_id'], unique=False)
    op.create_table('commission_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['commission_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ord_project', 'commission_orders', ['project_id'], unique=False)
    op.create_index('idx_ord_status', 'commission_orders', ['status'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rfq_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_samples_rfq', 'samples', ['rfq_id'], unique=False)
    op.create_table('subscription_subscribers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('tier_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sub_status', 'subscription_subscribers', ['status'], unique=False)
    op.create_index('idx_sub_tier', 'subscription_subscribers', ['tier_id'], unique=False)
    op.create_index('idx_sub_user', 'subscription_subscribers', ['user_id'], unique=False)
    op.create_table('quality_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sample_id', sa.String(length=32), nullable=True),
    sa.Column('aql_level', sa.String(length=10), nullable=True),
    sa.Column('defects', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('total_inspected', sa.Integer(), nullable=True),
    sa.Column('inspector_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qr_sample', 'quality_reports', ['sample_id'], unique=False)
    op.create_table('subtitles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('format_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subtitles_lang', 'subtitles', ['language'], unique=False)
    op.create_index('idx_subtitles_work', 'subtitles', ['work_id'], unique=False)
    op.create_table('video_frame_fingerprints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('video_work_id', sa.String(length=32), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vff_hash', 'video_frame_fingerprints', ['perceptual_hash'], unique=False)
    op.create_index('idx_vff_video', 'video_frame_fingerprints', ['video_work_id', 'frame_number'], unique=False)
    op.create_table('work_variant_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('variant_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=2000), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wvg_type', 'work_variant_groups', ['variant_type'], unique=False)
    op.create_index('idx_wvg_work', 'work_variant_groups', ['work_id'], unique=False)
    # Batch mode for SQLite FK constraints on existing tables
    with op.batch_alter_table('campaigns') as batch_op:
        batch_op.add_column(sa.Column('listing_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')
    op.add_column('licenses', sa.Column('listing_id', sa.String(length=32), nullable=True))
    op.create_index('idx_license_listing', 'licenses', ['listing_id'], unique=False)
    with op.batch_alter_table('licenses') as batch_op:
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')
    op.add_column('monitor_results', sa.Column('is_mock', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('listing_id', sa.String(length=32), nullable=True))
    with op.batch_alter_table('orders') as batch_op:
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')
    op.add_column('product_publishings', sa.Column('listing_id', sa.String(length=32), nullable=True))
    with op.batch_alter_table('product_publishings') as batch_op:
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='CASCADE')
    op.add_column('revenue_records', sa.Column('listing_id', sa.String(length=32), nullable=True))
    with op.batch_alter_table('revenue_records') as batch_op:
        batch_op.create_foreign_key(None, 'design_listings', ['listing_id'], ['id'], ondelete='SET NULL')
    op.add_column('works', sa.Column('is_project_package', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('project_files', sa.JSON(), nullable=True))
    op.add_column('works', sa.Column('is_raw_original', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('raw_sidecar_path', sa.String(length=2000), nullable=True))
    op.add_column('works', sa.Column('raw_processed_variant_id', sa.String(length=32), nullable=True))
    op.add_column('works', sa.Column('cull_status', sa.String(length=20), nullable=True))
    op.add_column('works', sa.Column('cull_rating', sa.Integer(), nullable=True))
    op.add_column('works', sa.Column('color_label', sa.String(length=20), nullable=True))
    op.alter_column('works', 'completion_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'completion_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('works', 'color_label')
    op.drop_column('works', 'cull_rating')
    op.drop_column('works', 'cull_status')
    op.drop_column('works', 'raw_processed_variant_id')
    op.drop_column('works', 'raw_sidecar_path')
    op.drop_column('works', 'is_raw_original')
    op.drop_column('works', 'project_files')
    op.drop_column('works', 'is_project_package')
    op.drop_constraint(None, 'revenue_records', type_='foreignkey')
    op.drop_column('revenue_records', 'listing_id')
    op.drop_constraint(None, 'product_publishings', type_='foreignkey')
    op.drop_column('product_publishings', 'listing_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'listing_id')
    op.drop_column('monitor_results', 'is_mock')
    op.drop_constraint(None, 'licenses', type_='foreignkey')
    op.drop_index('idx_license_listing', table_name='licenses')
    op.drop_column('licenses', 'listing_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index('idx_wvg_work', table_name='work_variant_groups')
    op.drop_index('idx_wvg_type', table_name='work_variant_groups')
    op.drop_table('work_variant_groups')
    op.drop_index('idx_vff_video', table_name='video_frame_fingerprints')
    op.drop_index('idx_vff_hash', table_name='video_frame_fingerprints')
    op.drop_table('video_frame_fingerprints')
    op.drop_index('idx_subtitles_work', table_name='subtitles')
    op.drop_index('idx_subtitles_lang', table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index('idx_qr_sample', table_name='quality_reports')
    op.drop_table('quality_reports')
    op.drop_index('idx_sub_user', table_name='subscription_subscribers')
    op.drop_index('idx_sub_tier', table_name='subscription_subscribers')
    op.drop_index('idx_sub_status', table_name='subscription_subscribers')
    op.drop_table('subscription_subscribers')
    op.drop_index('idx_samples_rfq', table_name='samples')
    op.drop_table('samples')
    op.drop_index('idx_ord_status', table_name='commission_orders')
    op.drop_index('idx_ord_project', table_name='commission_orders')
    op.drop_table('commission_orders')
    op.drop_index('idx_msg_sender', table_name='commission_messages')
    op.drop_index('idx_msg_project', table_name='commission_messages')
    op.drop_table('commission_messages')
    op.drop_table('video_fingerprint_config')
    op.drop_index('idx_tier_name', table_name='subscription_tiers')
    op.drop_index('idx_tier_active', table_name='subscription_tiers')
    op.drop_table('subscription_tiers')
    op.drop_index('idx_rfq_user', table_name='rfq_requests')
    op.drop_index('idx_rfq_status', table_name='rfq_requests')
    op.drop_table('rfq_requests')
    op.drop_index('idx_pff_ext', table_name='project_file_formats')
    op.drop_table('project_file_formats')
    op.drop_index('idx_comp_user', table_name='commission_projects')
    op.drop_index('idx_comp_status', table_name='commission_projects')
    op.drop_table('commission_projects')
    # ### end Alembic commands ###
